name: Update Ranking from WoW Progress
on: [push, workflow_dispatch]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get ranking from WoW Progress
        id: fetch-ranking
        uses: senmu/download-json-property-action@v1.0.0
        with:
          url: 'https://www.wowprogress.com/guild/us/wyrmrest-accord/Whisper/json_rank'
          property_path: realm_rank
      - run: echo ${{steps.fetch-ranking.outputs.value}}
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          dir: '_data'
          name: "wowprogress.json"
          json: '{ "realm_rank": ${{steps.fetch-ranking.outputs.value}} }'
      -run: cat _data/wowprogress.json

